
function createLevel1() {
    return new Level(
        [
            new Pufferfish('green'),
            new Pufferfish('orange'),
            new Pufferfish('red'),
            new Pufferfish('green'),
            new Pufferfish('orange'),
            new Pufferfish('red'),
            new Pufferfish('green'),
            new Pufferfish('orange'),
            new Endboss(),
            new Jellyfish('lila'),
            new Jellyfish('yellow'),
            new Jellyfish('green'),
            new Jellyfish('pink'),
            new Jellyfish('lila'),
            new Jellyfish('yellow'),
            new Jellyfish('green'),
            new Jellyfish('pink')
        ],
        [
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater(),
            new PoisonWater()
        ],
        [
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin(),
            new Coin()
        ],
        [
            new BackgroundObject("img/3.Background/Layers/5. Water/D1.png", -719 * 2),
            new BackgroundObject("img/3.Background/Layers/4.Fondo 2/D1.png", -719 * 2),
            new BackgroundObject("img/3.Background/Layers/3.Fondo 1/D1.png", -719 * 2),
            new BackgroundObject("img/3.Background/Layers/2. Floor/D1.png", -719 * 2),
            new BackgroundObject("img/3.Background/Layers/1. Light/D1.png", -719 * 2),
            new BackgroundObject("img/3.Background/Layers/5. Water/D2.png", -719),
            new BackgroundObject("img/3.Background/Layers/4.Fondo 2/D2.png", -719),
            new BackgroundObject("img/3.Background/Layers/3.Fondo 1/D2.png", -719),
            new BackgroundObject("img/3.Background/Layers/2. Floor/D2.png", -719),
            new BackgroundObject("img/3.Background/Layers/1. Light/D2.png", -719),
            new BackgroundObject("img/3.Background/Layers/5. Water/D1.png", 0),
            new BackgroundObject("img/3.Background/Layers/4.Fondo 2/D1.png", 0),
            new BackgroundObject("img/3.Background/Layers/3.Fondo 1/D1.png", 0),
            new BackgroundObject("img/3.Background/Layers/2. Floor/D1.png", 0),
            new BackgroundObject("img/3.Background/Layers/1. Light/D1.png", 0),
            new BackgroundObject("img/3.Background/Layers/5. Water/D2.png", 719),
            new BackgroundObject("img/3.Background/Layers/4.Fondo 2/D2.png", 719),
            new BackgroundObject("img/3.Background/Layers/3.Fondo 1/D2.png", 719),
            new BackgroundObject("img/3.Background/Layers/2. Floor/D2.png", 719),
            new BackgroundObject("img/3.Background/Layers/1. Light/D2.png", 719),
            new BackgroundObject("img/3.Background/Layers/5. Water/D1.png", 719 * 2),
            new BackgroundObject("img/3.Background/Layers/4.Fondo 2/D1.png", 719 * 2),
            new BackgroundObject("img/3.Background/Layers/3.Fondo 1/D1.png", 719 * 2),
            new BackgroundObject("img/3.Background/Layers/2. Floor/D1.png", 719 * 2),
            new BackgroundObject("img/3.Background/Layers/1. Light/D1.png", 719 * 2),
            new BackgroundObject("img/3.Background/Layers/5. Water/D2.png", 719 * 3),
            new BackgroundObject("img/3.Background/Layers/4.Fondo 2/D2.png", 719 * 3),
            new BackgroundObject("img/3.Background/Layers/3.Fondo 1/D2.png", 719 * 3),
            new BackgroundObject("img/3.Background/Layers/2. Floor/D2.png", 719 * 3),
            new BackgroundObject("img/3.Background/Layers/1. Light/D2.png", 719 * 3),
            new BackgroundObject("img/3.Background/Layers/5. Water/D1.png", 719 * 4),
            new BackgroundObject("img/3.Background/Layers/4.Fondo 2/D1.png", 719 * 4),
            new BackgroundObject("img/3.Background/Layers/3.Fondo 1/D1.png", 719 * 4),
            new BackgroundObject("img/3.Background/Layers/2. Floor/D1.png", 719 * 4),
            new BackgroundObject("img/3.Background/Layers/1. Light/D1.png", 719 * 4),
            new BackgroundObject("img/3.Background/Layers/5. Water/D2.png", 719 * 5),
            new BackgroundObject("img/3.Background/Layers/4.Fondo 2/D2.png", 719 * 5),
            new BackgroundObject("img/3.Background/Layers/3.Fondo 1/D2.png", 719 * 5),
            new BackgroundObject("img/3.Background/Layers/2. Floor/D2.png", 719 * 5),
            new BackgroundObject("img/3.Background/Layers/1. Light/D2.png", 719 * 5),
            new BackgroundObject("img/3.Background/Layers/5. Water/D1.png", 719 * 6),
            new BackgroundObject("img/3.Background/Layers/4.Fondo 2/D1.png", 719 * 6),
            new BackgroundObject("img/3.Background/Layers/3.Fondo 1/D1.png", 719 * 6),
            new BackgroundObject("img/3.Background/Layers/2. Floor/D1.png", 719 * 6),
            new BackgroundObject("img/3.Background/Layers/1. Light/D1.png", 719 * 6),
        ]
    );
}